# Generated by Django 5.1.15 on 2026-06-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountEmailaddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254, unique=True)),
                ('verified', models.BooleanField()),
                ('primary', models.BooleanField()),
            ],
            options={
                'db_table': 'account_emailaddress',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountEmailconfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('sent', models.DateTimeField(blank=True, null=True)),
                ('key', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'account_emailconfirmation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgentDocument',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField()),
                ('sharepoint', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'agent_document',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AgentDocumentchunk',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('embedding', models.TextField()),
                ('page_number', models.IntegerField()),
            ],
            options={
                'db_table': 'agent_documentchunk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthtokenToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'authtoken_token',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'django_site',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KgpCompletedOrders',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('build', models.TextField()),
                ('tethers_total', models.BigIntegerField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('production_shift', models.IntegerField(blank=True, null=True)),
                ('cable_type', models.TextField(blank=True, null=True)),
                ('result_status', models.TextField(blank=True, null=True)),
                ('started_date', models.DateTimeField(blank=True, null=True)),
                ('workplace', models.TextField(blank=True, null=True)),
                ('line', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kgp_completed_orders',
                'db_table_comment': 'This table will get the orders that has been completed in final test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KgpCuttingMachines',
            fields=[
                ('machine_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('machine_code', models.TextField()),
                ('machine_english_name', models.TextField(blank=True, null=True)),
                ('machine_spanish_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kgp_cutting_machines',
                'db_table_comment': "Stores plant's cutting machines",
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KgpCuttingResults',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entered_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('master_reel', models.TextField(blank=True, null=True)),
                ('scrap', models.BooleanField(blank=True, null=True)),
                ('stack_id', models.SmallIntegerField(blank=True, db_column='stack_id', null=True)),
                ('production_shift', models.SmallIntegerField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('has_master_reel', models.BooleanField()),
            ],
            options={
                'db_table': 'kgp_cutting_results',
                'db_table_comment': 'Stores cutting machines set up',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KgpCuttingWipAreas',
            fields=[
                ('cutting_wip_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cutting_wip_code', models.TextField(blank=True, null=True)),
                ('internal_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kgp_cutting_wip_areas',
                'db_table_comment': 'Stores cutting areas. Once and order has been cuted, it will be located into one of this, waiting for a handler to set it up on a production line.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KgpEmployees',
            fields=[
                ('employee', models.BigAutoField(primary_key=True, serialize=False)),
                ('employee_number', models.BigIntegerField(unique=True)),
                ('employee_name', models.TextField(blank=True, null=True)),
                ('shift', models.IntegerField()),
                ('supervisor', models.TextField(blank=True, null=True)),
                ('is_auditor', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kgp_employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KgpFinaltestMetricsDaily',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('workplace', models.TextField()),
                ('fibers_per_hour', models.TextField()),
                ('failed_fibers_count', models.BigIntegerField()),
                ('scrap_count', models.BigIntegerField()),
                ('shift', models.SmallIntegerField()),
                ('updated_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'kgp_finaltest_metrics_daily',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KgpFinaltestResults',
            fields=[
                ('entered_date', models.DateTimeField()),
                ('employee_number', models.BigIntegerField(blank=True, null=True)),
                ('workplace', models.TextField(blank=True, null=True)),
                ('passed_fibers', models.BigIntegerField(blank=True, null=True)),
                ('failed_fibers', models.TextField(blank=True, null=True)),
                ('finished', models.BooleanField(blank=True, null=True)),
                ('scrap', models.BooleanField(blank=True, null=True)),
                ('updated_date', models.TextField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('production_hour', models.SmallIntegerField(blank=True, null=True)),
                ('production_shift', models.SmallIntegerField(blank=True, null=True)),
                ('hold_time_total', models.IntegerField(blank=True, null=True)),
                ('active_time_total', models.IntegerField(blank=True, null=True)),
                ('time_total', models.IntegerField(blank=True, null=True)),
                ('rework_auditor', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kgp_finaltest_results',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KgpFinaltestWipAreas',
            fields=[
                ('finaltest_wip_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('creatfinaltest_wip_codeed_at', models.TextField()),
                ('internal_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kgp_finaltest_wip_areas',
                'db_table_comment': 'Stores final test/packaging wip codes. Once final test has been done, order will be assigned to one of this areas.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KgpFinaltestWipResults',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entered_date', models.DateTimeField(blank=True, null=True)),
                ('employee_number', models.TextField(blank=True, null=True)),
                ('was_packaged', models.BooleanField(blank=True, null=True)),
                ('production_shift', models.BigIntegerField(blank=True, null=True)),
                ('production_cell', models.BigIntegerField(blank=True, null=True)),
                ('production_table', models.TextField(blank=True, null=True)),
                ('reel_id', models.TextField(blank=True, db_column='reel_id', null=True)),
                ('carret_size', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kgp_finaltest_wip_results',
                'db_table_comment': 'Stores if and order was or not packaged.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KgpOrdersPriority',
            fields=[
                ('priority_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('priority_code', models.TextField()),
                ('priority_english_name', models.TextField(blank=True, null=True)),
                ('priority_spanish_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kgp_orders_priority',
                'db_table_comment': 'Priority codes for planned orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KgpOrdersStatus',
            fields=[
                ('status', models.AutoField(db_column='status_id', primary_key=True, serialize=False)),
                ('status_code', models.TextField(blank=True, null=True, unique=True)),
                ('status_description', models.TextField(blank=True, null=True)),
                ('status_description_spanish', models.TextField(blank=True, null=True)),
                ('internal_descrption', models.TextField(blank=True, db_comment='This section is to explain what every code is', null=True)),
            ],
            options={
                'db_table': 'kgp_orders_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KgpOvertimeReasons',
            fields=[
                ('overtime', models.BigAutoField(primary_key=True, serialize=False)),
                ('overtime_desciption', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'kgp_overtime_reasons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KgpPlanningOrders',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('original_deliver_date', models.DateTimeField(blank=True, null=True)),
                ('production_deliver_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kgp_planning_orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KgpProcessFailCodes',
            fields=[
                ('fail', models.AutoField(db_column='fail_id', primary_key=True, serialize=False)),
                ('fail_description', models.TextField()),
            ],
            options={
                'db_table': 'kgp_process_fail_codes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KgpProductionOrders',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entered_date', models.DateTimeField()),
                ('build', models.TextField(blank=True, db_column='build_id', null=True, unique=True)),
                ('fiber_count', models.BigIntegerField(blank=True, null=True)),
                ('planned_fibers', models.BigIntegerField(blank=True, null=True)),
                ('spare_fibers', models.BigIntegerField(blank=True, null=True)),
                ('tethers', models.BigIntegerField(blank=True, null=True)),
                ('taps', models.BigIntegerField(blank=True, null=True)),
                ('cable_type', models.TextField(blank=True, null=True)),
                ('cable_length', models.BigIntegerField(blank=True, null=True)),
                ('order_type', models.TextField(blank=True, null=True)),
                ('installation_type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kgp_production_orders',
                'db_table_comment': 'Any new orders added to the database',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KgpProductionOrderSetup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('updated_date', models.DateTimeField()),
                ('build', models.TextField(unique=True)),
                ('location_setup', models.TextField(blank=True, null=True)),
                ('tethers_registered', models.IntegerField(blank=True, null=True)),
                ('locations_registered', models.IntegerField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('attempt_number', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kgp_production_order_setup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KgpProductionProcess',
            fields=[
                ('process', models.AutoField(db_column='process_id', primary_key=True, serialize=False)),
                ('process_name', models.TextField(unique=True)),
                ('estimated_time', models.IntegerField()),
                ('process_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kgp_production_process',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KgpProductionRework',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entered_date', models.DateTimeField()),
                ('build', models.TextField(blank=True, null=True)),
                ('workplace', models.SmallIntegerField(blank=True, null=True)),
                ('rework_auditor', models.IntegerField(blank=True, null=True)),
                ('shift', models.SmallIntegerField(blank=True, null=True)),
                ('employee_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kgp_production_rework',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KgpProductionScrap',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entered_date', models.DateTimeField()),
                ('build', models.TextField(blank=True, null=True)),
                ('workplace', models.SmallIntegerField(blank=True, null=True)),
                ('process', models.SmallIntegerField(blank=True, null=True)),
                ('employee_number', models.IntegerField(blank=True, null=True)),
                ('scrap_auditor', models.IntegerField(blank=True, null=True)),
                ('tap_number', models.SmallIntegerField(blank=True, null=True)),
                ('global_tether', models.SmallIntegerField(blank=True, null=True)),
                ('scrap', models.SmallIntegerField(blank=True, null=True)),
                ('shift', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kgp_production_scrap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KgpProductionWorkstations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cell', models.SmallIntegerField(blank=True, null=True)),
                ('line', models.SmallIntegerField(blank=True, null=True)),
                ('station', models.SmallIntegerField(blank=True, null=True)),
                ('workplace', models.SmallIntegerField(blank=True, null=True, unique=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('working_build', models.TextField(blank=True, null=True)),
                ('working_build_location', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kgp_production_workstations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KgpReworkCodes',
            fields=[
                ('rework', models.BigAutoField(primary_key=True, serialize=False)),
                ('rework_description', models.TextField(blank=True, null=True)),
                ('rework_code', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kgp_rework_codes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KgpScrapCodes',
            fields=[
                ('scrap', models.BigAutoField(primary_key=True, serialize=False)),
                ('scrap_description', models.TextField(blank=True, null=True)),
                ('scrap_code', models.TextField(blank=True, null=True, unique=True)),
                ('scrap_description_spanish', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kgp_scrap_codes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KgpSubassembleKitResults',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entered_date', models.DateTimeField(blank=True, null=True)),
                ('employee_number', models.TextField(blank=True, null=True)),
                ('cable_type', models.TextField(blank=True, null=True)),
                ('registered_tethers', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kgp_subassemble_kit_results',
                'db_table_comment': "Stores order's status on sub-assemble. produices_tethers should be equals to production_orders.tethers in order to set as completed",
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KgpSubassemblyResults',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entered_date', models.DateTimeField()),
                ('kit_delivered', models.BooleanField(blank=True, null=True)),
                ('employee_number', models.BigIntegerField(blank=True, null=True)),
                ('updated_date', models.TextField(blank=True, null=True)),
                ('scrap', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kgp_subassembly_results',
                'db_table_comment': 'This table will get the subensamble orders that are in WIP',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KgpSubensambleResults',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entered_date', models.DateTimeField()),
                ('build', models.TextField(blank=True, null=True)),
                ('tether_description', models.TextField(blank=True, null=True)),
                ('tether_quantity', models.BigIntegerField(blank=True, null=True)),
                ('finished', models.BooleanField(blank=True, null=True)),
                ('employee_number', models.BigIntegerField(blank=True, null=True)),
                ('updated_date', models.TextField(blank=True, null=True)),
                ('tap_number', models.IntegerField(blank=True, null=True)),
                ('local_tether', models.IntegerField(blank=True, null=True)),
                ('global_tether', models.IntegerField(blank=True, null=True)),
                ('fail', models.IntegerField(blank=True, null=True)),
                ('rework', models.BooleanField(blank=True, null=True)),
                ('scrap', models.BooleanField(blank=True, null=True)),
                ('hold_time_total', models.IntegerField(blank=True, null=True)),
                ('active_time_total', models.IntegerField(blank=True, null=True)),
                ('time_total', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kgp_subensamble_results',
                'db_table_comment': 'This table will get the subensamble orders that are in WIP',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KgpTest2MetricsDaily',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cell', models.IntegerField()),
                ('tethers_per_hour', models.TextField()),
                ('scrap_count', models.IntegerField()),
                ('orders_scrapped', models.TextField()),
                ('openned_count', models.IntegerField()),
                ('orders_openned', models.TextField()),
                ('completed_count', models.IntegerField()),
                ('orders_completed', models.TextField()),
                ('shift', models.IntegerField()),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kgp_test2_metrics_daily',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KgpTest2Results',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entered_date', models.DateTimeField(blank=True, null=True)),
                ('employee_number', models.BigIntegerField(blank=True, null=True)),
                ('workplace', models.TextField(blank=True, null=True)),
                ('tethers_completed', models.BigIntegerField(blank=True, null=True)),
                ('build_attempt', models.BigIntegerField(blank=True, null=True)),
                ('scrap', models.BooleanField(blank=True, null=True)),
                ('updated_date', models.TextField(blank=True, null=True)),
                ('production_cell', models.IntegerField(blank=True, null=True)),
                ('production_hour', models.IntegerField(blank=True, null=True)),
                ('production_shift', models.IntegerField(blank=True, null=True)),
                ('tethers_total', models.BigIntegerField(blank=True, null=True)),
                ('result_status', models.TextField(blank=True, null=True)),
                ('fail_quantity', models.IntegerField(blank=True, null=True)),
                ('hold_time_total', models.IntegerField(blank=True, null=True)),
                ('active_time_total', models.IntegerField(blank=True, null=True)),
                ('time_total', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kgp_test2_results',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KpgProcessFails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('global_tether', models.IntegerField(blank=True, null=True)),
                ('entered_date', models.DateTimeField()),
                ('employee_number', models.BigIntegerField(blank=True, null=True)),
                ('workplace', models.TextField(blank=True, null=True)),
                ('fail_amount', models.IntegerField()),
                ('shift', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kpg_process_fails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KpgProductionProcessResults',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entered_date', models.DateTimeField()),
                ('employee_number', models.BigIntegerField(blank=True, null=True)),
                ('workplace', models.TextField(blank=True, null=True)),
                ('tap_number', models.IntegerField(blank=True, null=True)),
                ('local_tether', models.IntegerField(blank=True, null=True)),
                ('global_tether', models.IntegerField(blank=True, null=True)),
                ('hold_time_total', models.IntegerField(blank=True, null=True)),
                ('active_time_total', models.IntegerField(blank=True, null=True)),
                ('time_total', models.IntegerField(blank=True, null=True)),
                ('tether', models.IntegerField(blank=True, db_column='tether_id', editable=False, null=True)),
                ('process_start_time', models.TextField(blank=True, null=True)),
                ('process_finish_time', models.TextField(blank=True, null=True)),
                ('attempt_number', models.SmallIntegerField(blank=True, null=True)),
                ('shift', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kpg_production_process_results',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QualityAuditors',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(blank=True, max_length=150, null=True)),
                ('shift', models.BigIntegerField(blank=True, null=True)),
                ('supervisor', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'quality_auditors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocialaccountSocialaccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=200)),
                ('uid', models.CharField(max_length=191)),
                ('last_login', models.DateTimeField()),
                ('date_joined', models.DateTimeField()),
                ('extra_data', models.JSONField()),
            ],
            options={
                'db_table': 'socialaccount_socialaccount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocialaccountSocialapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('client', models.CharField(max_length=191)),
                ('secret', models.CharField(max_length=191)),
                ('key', models.CharField(max_length=191)),
                ('provider', models.CharField(max_length=200)),
                ('settings', models.JSONField()),
            ],
            options={
                'db_table': 'socialaccount_socialapp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocialaccountSocialappSites',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'socialaccount_socialapp_sites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocialaccountSocialtoken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('token_secret', models.TextField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'socialaccount_socialtoken',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TetherTypes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tether', models.TextField(blank=True, null=True)),
                ('tether_description', models.TextField(blank=True, null=True)),
                ('connector_type', models.TextField(blank=True, null=True)),
                ('order_type', models.TextField(blank=True, null=True)),
                ('installation_type', models.TextField(blank=True, null=True)),
                ('situation', models.TextField(blank=True, null=True)),
                ('tether_length', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tether_types',
                'managed': False,
            },
        ),
    ]
