# Generated by Django 6.0 on 2025-12-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KgpEmployees',
            fields=[
                ('employee_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('employee_number', models.BigIntegerField(unique=True)),
                ('employee_name', models.TextField(blank=True, null=True)),
                ('shift', models.IntegerField()),
                ('supervisor', models.TextField(blank=True, null=True)),
                ('is_auditor', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kgp_employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KgpProcessFailCodes',
            fields=[
                ('fail_id', models.AutoField(primary_key=True, serialize=False)),
                ('fail_description', models.TextField()),
            ],
            options={
                'db_table': 'kgp_process_fail_codes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KgpProductionOrders',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entered_date', models.DateTimeField()),
                ('build_id', models.TextField(blank=True, null=True, unique=True)),
                ('fiber_count', models.BigIntegerField(blank=True, null=True)),
                ('planned_fibers', models.BigIntegerField(blank=True, null=True)),
                ('spare_fibers', models.BigIntegerField(blank=True, null=True)),
                ('tethers', models.BigIntegerField(blank=True, null=True)),
                ('taps', models.BigIntegerField(blank=True, null=True)),
                ('cable_type', models.TextField(blank=True, null=True)),
                ('cable_length', models.BigIntegerField(blank=True, null=True)),
                ('order_type', models.TextField(blank=True, null=True)),
                ('installation_type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kgp_production_orders',
                'db_table_comment': 'Any new orders added to the database',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KgpProductionProcess',
            fields=[
                ('process_id', models.AutoField(primary_key=True, serialize=False)),
                ('process_name', models.TextField(unique=True)),
                ('estimated_time', models.IntegerField()),
            ],
            options={
                'db_table': 'kgp_production_process',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KgpReworkCodes',
            fields=[
                ('rework_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rework_description', models.TextField(blank=True, null=True)),
                ('rework_code', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kgp_rework_codes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KgpScrapCodes',
            fields=[
                ('scrap_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('scrap_description', models.TextField(blank=True, null=True)),
                ('scrap_code', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'kgp_scrap_codes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KgpTest2Results',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entered_date', models.DateTimeField(blank=True, null=True)),
                ('employee_number', models.BigIntegerField(blank=True, null=True)),
                ('workplace', models.TextField(blank=True, null=True)),
                ('tethers_completed', models.BigIntegerField(blank=True, null=True)),
                ('build_attempt', models.BigIntegerField(blank=True, null=True)),
                ('scrap', models.BooleanField(blank=True, null=True)),
                ('updated_date', models.TextField(blank=True, null=True)),
                ('production_cell', models.IntegerField(blank=True, null=True)),
                ('production_hour', models.IntegerField(blank=True, null=True)),
                ('production_shift', models.IntegerField(blank=True, null=True)),
                ('tethers_total', models.BigIntegerField(blank=True, null=True)),
                ('result_status', models.TextField(blank=True, null=True)),
                ('fail_quantity', models.IntegerField(blank=True, null=True)),
                ('hold_time_total', models.IntegerField(blank=True, null=True)),
                ('active_time_total', models.IntegerField(blank=True, null=True)),
                ('time_total', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kgp_test2_results',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QualityAuditors',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(blank=True, null=True)),
                ('shift', models.BigIntegerField(blank=True, null=True)),
                ('supervisor', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'quality_auditors',
                'managed': False,
            },
        ),
    ]
