# Generated by Django 5.1.15 on 2026-02-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KgpFinaltestResults',
            fields=[
                ('entered_date', models.DateTimeField()),
                ('employee_number', models.BigIntegerField(blank=True, null=True)),
                ('workplace', models.TextField(blank=True, null=True)),
                ('passed_fibers', models.BigIntegerField(blank=True, null=True)),
                ('failed_fibers', models.TextField(blank=True, null=True)),
                ('finished', models.BooleanField(blank=True, null=True)),
                ('scrap', models.BooleanField(blank=True, null=True)),
                ('updated_date', models.TextField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('production_hour', models.SmallIntegerField(blank=True, null=True)),
                ('production_shift', models.SmallIntegerField(blank=True, null=True)),
                ('hold_time_total', models.IntegerField(blank=True, null=True)),
                ('active_time_total', models.IntegerField(blank=True, null=True)),
                ('time_total', models.IntegerField(blank=True, null=True)),
                ('rework_auditor', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kgp_finaltest_results',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KpgProcessFails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('global_tether', models.IntegerField(blank=True, null=True)),
                ('entered_date', models.DateTimeField()),
                ('employee_number', models.BigIntegerField(blank=True, null=True)),
                ('workplace', models.TextField(blank=True, null=True)),
                ('fail_amount', models.IntegerField()),
            ],
            options={
                'db_table': 'kpg_process_fails',
                'managed': False,
            },
        ),
    ]
